package edu.nesterenko.airline.command;

public enum CommandEnum {
	ADD_AIRBUS, ADD_FREIGHTER, DELETE, FIND_ALL, FIND_BY_FUEL_CONSUMPTION, 
	CALCULATE_GENERAL_BEARING_CAPACITY, CALCULATE_GENERAL_CAPACITY,
	SORT_AIRPLAINS_BY_MAX_RANGE, LOAD_WITH_SAX, LOAD_WITH_STAX,
	LOAD_WITH_DOM;	
}
