-- MySQL Script generated by MySQL Workbench
-- 09/18/15 08:54:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema touroperator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema touroperator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `touroperator` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `touroperator` ;

-- -----------------------------------------------------
-- Table `touroperator`.`rest_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`rest_type` (
  `rest_type_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rest_type_name` VARCHAR(255) NOT NULL COMMENT '',
  `rest_type_description` TEXT NULL COMMENT '',
  PRIMARY KEY (`rest_type_id`)  COMMENT '',
  UNIQUE INDEX `rest_type_name_UNIQUE` (`rest_type_name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `country_name` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`country_id`)  COMMENT '',
  UNIQUE INDEX `country_name_UNIQUE` (`country_name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`rest_type_2_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`rest_type_2_country` (
  `rest_type_2_country_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rest_type_id` INT NOT NULL COMMENT '',
  `country_id` INT NOT NULL COMMENT '',
  `rest_type_2_country_description` TEXT NULL COMMENT '',
  PRIMARY KEY (`rest_type_2_country_id`)  COMMENT '',
  INDEX `rest_type_id_idx` (`rest_type_id` ASC)  COMMENT '',
  INDEX `country_id_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `rest_type_id`
    FOREIGN KEY (`rest_type_id`)
    REFERENCES `touroperator`.`rest_type` (`rest_type_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `touroperator`.`country` (`country_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `city_name` VARCHAR(255) NULL COMMENT '',
  `city_description` VARCHAR(255) NULL COMMENT '',
  `country_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`city_id`)  COMMENT '',
  INDEX `NAME_INDEX` (`city_name` ASC)  COMMENT '',
  INDEX `country_id_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `touroperator`.`country` (`country_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`resort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`resort` (
  `resort_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `resort_name` VARCHAR(255) NOT NULL COMMENT '',
  `resort_description` TEXT NULL COMMENT '',
  `city_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`resort_id`)  COMMENT '',
  INDEX `NAME_INDEX` (`resort_name` ASC)  COMMENT '',
  INDEX `city_id_idx` (`city_id` ASC)  COMMENT '',
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `touroperator`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`resort_hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`resort_hotel` (
  `resort_hotel_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `resort_hotel_stars` ENUM('1', '2', '3', '4', '5') NULL COMMENT '',
  `resort_hotel_name` VARCHAR(45) NULL COMMENT '',
  `resort_hotel_description` TEXT NULL COMMENT '',
  `resort_id` INT NULL COMMENT '',
  PRIMARY KEY (`resort_hotel_id`)  COMMENT '',
  INDEX `INDEX_NAME` (`resort_hotel_name` ASC)  COMMENT '',
  INDEX `resort_id_idx` (`resort_id` ASC)  COMMENT '',
  CONSTRAINT `resort_id`
    FOREIGN KEY (`resort_id`)
    REFERENCES `touroperator`.`resort` (`resort_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`excursion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`excursion` (
  `excursion_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `excursion_name` VARCHAR(255) NULL COMMENT '',
  `excursion_description` VARCHAR(255) NULL COMMENT '',
  `excursion_cost` DECIMAL NULL COMMENT '',
  `excursion_begin_date` DATE NULL COMMENT '',
  `excursion_end_date` DATE NULL COMMENT '',
  `excursion_days` INT NULL COMMENT '',
  `excursion_food` VARCHAR(255) NULL COMMENT '',
  `excursion_path` TEXT NULL COMMENT '',
  PRIMARY KEY (`excursion_id`)  COMMENT '',
  INDEX `INDEX_COST` (`excursion_cost` ASC)  COMMENT '',
  INDEX `INDEX_NAME` (`excursion_name` ASC)  COMMENT '',
  INDEX `INDEX_BEGIN_DATE` (`excursion_begin_date` ASC)  COMMENT '',
  INDEX `INDEX_END_DATE` (`excursion_end_date` ASC)  COMMENT '',
  INDEX `INDEX_FOOD` (`excursion_food` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`tour` (
  `tour_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tour_name` VARCHAR(255) NULL COMMENT '',
  `tour_description` TEXT NULL COMMENT '',
  `tour_cost` DECIMAL NULL COMMENT '',
  `tour_begin_date` DATE NOT NULL COMMENT '',
  `tour_end_date` DATE NOT NULL COMMENT '',
  `tour_days` INT NOT NULL COMMENT '',
  `tour_food` VARCHAR(255) NOT NULL COMMENT '',
  `tour_path` TEXT NULL COMMENT '',
  `tour_path_time` INT NULL COMMENT '',
  `rest_type_id` INT NOT NULL COMMENT '',
  `hotel_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`tour_id`)  COMMENT '',
  INDEX `INDEX_NAME` (`tour_name` ASC)  COMMENT '',
  INDEX `rest_type_idx` (`rest_type_id` ASC)  COMMENT '',
  INDEX `hotel_idx` (`hotel_id` ASC)  COMMENT '',
  INDEX `INDEX_COST` (`tour_cost` ASC)  COMMENT '',
  INDEX `INDEX_FOOD` (`tour_food` ASC)  COMMENT '',
  CONSTRAINT `rest_type`
    FOREIGN KEY (`rest_type_id`)
    REFERENCES `touroperator`.`rest_type` (`rest_type_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `touroperator`.`resort_hotel` (`resort_hotel_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`hotel` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hotel_stars` ENUM('1', '2', '3', '4', '5') NULL COMMENT '',
  `hotel_name` VARCHAR(45) NULL COMMENT '',
  `hotel_description` TEXT NULL COMMENT '',
  `city_id` INT NULL COMMENT '',
  PRIMARY KEY (`hotel_id`)  COMMENT '',
  INDEX `INDEX_NAME` (`hotel_name` ASC)  COMMENT '',
  INDEX `city_id_idx` (`city_id` ASC)  COMMENT '',
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `touroperator`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`visit_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`visit_city` (
  `excursion_id` INT NOT NULL COMMENT '',
  `city_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`excursion_id`, `city_id`)  COMMENT '',
  INDEX `city_id_idx` (`city_id` ASC)  COMMENT '',
  CONSTRAINT `excursion_id`
    FOREIGN KEY (`excursion_id`)
    REFERENCES `touroperator`.`excursion` (`excursion_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `touroperator`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`visit_hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`visit_hotel` (
  `excursion_id` INT NOT NULL COMMENT '',
  `hotel_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`excursion_id`, `hotel_id`)  COMMENT '',
  INDEX `city_id0_idx` (`hotel_id` ASC)  COMMENT '',
  CONSTRAINT `excursion_id`
    FOREIGN KEY (`excursion_id`)
    REFERENCES `touroperator`.`excursion` (`excursion_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_id`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `touroperator`.`hotel` (`hotel_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `client_login` VARCHAR(20) NULL COMMENT '',
  `client_hash` VARCHAR(128) NULL COMMENT '',
  `client_salt` VARCHAR(18) NULL COMMENT '',
  `client_email` VARCHAR(255) NULL COMMENT '',
  `client_type` ENUM('ADMIN', 'USER') NULL COMMENT '',
  PRIMARY KEY (`client_id`)  COMMENT '',
  UNIQUE INDEX `client_login_UNIQUE` (`client_login` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`ordered_tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`ordered_tour` (
  `ordered_tour_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ordered_tour_date` DATE NULL COMMENT '',
  `ordered_tour_money` DECIMAL NOT NULL COMMENT '',
  `tour_id` INT NULL COMMENT '',
  `client_id` INT NULL COMMENT '',
  PRIMARY KEY (`ordered_tour_id`)  COMMENT '',
  INDEX `client_id _idx` (`client_id` ASC)  COMMENT '',
  INDEX `tour_id_idx` (`tour_id` ASC)  COMMENT '',
  CONSTRAINT `client_id `
    FOREIGN KEY (`client_id`)
    REFERENCES `touroperator`.`client` (`client_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tour_id`
    FOREIGN KEY (`tour_id`)
    REFERENCES `touroperator`.`tour` (`tour_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touroperator`.`ordered_excursion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touroperator`.`ordered_excursion` (
  `ordered_excursion_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ordered_excursion_date` DATE NOT NULL COMMENT '',
  `ordered_excursion_money` DECIMAL NOT NULL COMMENT '',
  `client_id` INT NOT NULL COMMENT '',
  `excursion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ordered_excursion_id`)  COMMENT '',
  INDEX `client_id_idx` (`client_id` ASC)  COMMENT '',
  INDEX `excursion_id_idx` (`excursion_id` ASC)  COMMENT '',
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `touroperator`.`client` (`client_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `excursion_id`
    FOREIGN KEY (`excursion_id`)
    REFERENCES `touroperator`.`excursion` (`excursion_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
